# Generated by Django 4.2.23 on 2025-07-06 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0001_initial'),
    ]

    operations = [
        # Добавляем новые поля в ShiftType
        migrations.AddField(
            model_name='shifttype',
            name='shift_pattern',
            field=models.CharField(
                choices=[
                    ('daily', 'Ежедневная'),
                    ('weekly', 'Недельная (5/2)'),
                    ('weekly_alt', 'Недельная (2/2)'),
                    ('monthly', 'Месячная'),
                    ('custom', 'Пользовательская'),
                ],
                default='daily',
                max_length=20,
                verbose_name='Паттерн смены'
            ),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='is_overnight',
            field=models.BooleanField(
                default=False,
                verbose_name='Ночная смена (с 20:00 до 08:00)'
            ),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='working_days',
            field=models.CharField(
                default='1,2,3,4,5',
                max_length=50,
                verbose_name='Рабочие дни (1-Пн, 2-Вт, 3-Ср, 4-Чт, 5-Пт, 6-Сб, 7-Вс)'
            ),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='rest_days',
            field=models.CharField(
                default='6,7',
                max_length=50,
                verbose_name='Выходные дни (1-Пн, 2-Вт, 3-Ср, 4-Чт, 5-Пт, 6-Сб, 7-Вс)'
            ),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='shift_duration_hours',
            field=models.IntegerField(
                default=8,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(24)
                ],
                verbose_name='Длительность смены (часов)'
            ),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='color',
            field=models.CharField(
                default='#007bff',
                max_length=7,
                verbose_name='Цвет смены (HEX)'
            ),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        # Изменяем порядок сортировки
        migrations.AlterModelOptions(
            name='shifttype',
            options={
                'ordering': ['department', 'start_time'],
                'verbose_name': 'Тип смены',
                'verbose_name_plural': 'Типы смен'
            },
        ),
    ]
