# Generated by Django 4.2.23 on 2025-07-06 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0002_auto_20250706_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttype',
            name='rest_days',
        ),
        migrations.RemoveField(
            model_name='shifttype',
            name='shift_duration_hours',
        ),
        migrations.RemoveField(
            model_name='shifttype',
            name='shift_pattern',
        ),
        migrations.AddField(
            model_name='shift',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время окончания'),
        ),
        migrations.AddField(
            model_name='shift',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время начала'),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменена'),
        ),
        migrations.AddField(
            model_name='shift',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='custom_interval_days',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Интервал в днях (для пользовательской периодичности)'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='day_of_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='День месяца (для месячных смен)'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='duration_hours',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Длительность смены (часов)'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания действия (необязательно)'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='periodicity',
            field=models.CharField(choices=[('daily', 'Каждый день'), ('every_2_days', 'Через день'), ('every_3_days', 'Каждые 3 дня'), ('weekly', 'Раз в неделю'), ('biweekly', 'Раз в две недели'), ('monthly', 'Раз в месяц'), ('custom', 'Пользовательская')], default='daily', max_length=20, verbose_name='Периодичность смены'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала действия (необязательно)'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания смены'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='is_overnight',
            field=models.BooleanField(default=False, verbose_name='Ночная смена'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название типа смены'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала смены'),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='working_days',
            field=models.CharField(default='1,2,3,4,5', max_length=50, verbose_name='Рабочие дни недели (1-Пн, 2-Вт, 3-Ср, 4-Чт, 5-Пт, 6-Сб, 7-Вс)'),
        ),
    ]
