# Generated by Django 4.2.23 on 2025-07-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0003_remove_shifttype_rest_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='shift',
        ),
    ]
