# Generated by Django 4.2.23 on 2025-07-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0004_remove_shift_from_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskreport',
            name='shift_log',
        ),
    ]
