# Generated by Django 4.2.23 on 2025-07-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0005_remove_taskreport_shift_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created', 'Создано'), ('updated', 'Обновлено'), ('deleted', 'Удалено'), ('status_changed', 'Статус изменен'), ('assigned', 'Назначено'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], max_length=100, verbose_name='Действие'),
        ),
    ]
