# Generated by Django 4.2.23 on 2025-07-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0006_activitylog_description_alter_activitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к заданию'),
        ),
    ]
