# Generated by Django 4.2.23 on 2025-07-15 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0008_dailyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255, verbose_name='Что списали')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сколько списали')),
                ('destination', models.CharField(max_length=255, verbose_name='Куда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время списания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_log.employee', verbose_name='Кем списано')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_log.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Списание материала',
                'verbose_name_plural': 'Списания материалов',
                'ordering': ['-created_at'],
            },
        ),
    ]
