# Generated by Django 4.2.23 on 2025-07-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0010_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='project',
            field=models.CharField(blank=True, max_length=100, verbose_name='Проект'),
        ),
    ]
