# Generated by Django 4.2.23 on 2025-07-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0012_project_alter_note_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='shift_log.employee', verbose_name='Сотрудник')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='shift_log.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача проекта',
                'verbose_name_plural': 'Задачи проектов',
                'ordering': ['-created_at'],
            },
        ),
    ]
