# Generated by Django 4.2.23 on 2025-07-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0013_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время исполнения'),
        ),
    ]
