# Generated by Django 4.2.23 on 2025-07-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0014_projecttask_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='project',
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название'),
        ),
    ]
