# Generated by Django 4.2.23 on 2025-07-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0015_remove_note_project_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialwriteoff',
            name='unit',
            field=models.CharField(choices=[('m', 'м'), ('pcs', 'шт')], default='pcs', max_length=10),
        ),
    ]
