# Generated by Django 4.2.23 on 2025-07-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0016_materialwriteoff_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('maintenance', 'Обслуживание'), ('development', 'Разработка'), ('support', 'Поддержка'), ('emergency', 'Экстренная'), ('routine', 'Рутинная'), ('other_damage', 'Прочая поломка')], default='routine', max_length=20, verbose_name='Тип задачи'),
        ),
    ]
