# Generated by Django 4.2.23 on 2025-07-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0017_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_scope',
            field=models.CharField(choices=[('individual', 'Индивидуальная'), ('general', 'Общая')], default='individual', max_length=20, verbose_name='Тип назначения'),
        ),
    ]
