# Generated by Django 4.2.23 on 2025-08-08 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0019_alter_task_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='daily_reports/photos/', verbose_name='Фотография')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись к фотографии')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shift_log.dailyreport', verbose_name='Ежедневный отчет')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_log.employee', verbose_name='Загружено')),
            ],
            options={
                'verbose_name': 'Фотография ежедневного отчета',
                'verbose_name_plural': 'Фотографии ежедневных отчетов',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
