# Generated by Django 4.2.23 on 2025-09-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0020_dailyreportphoto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='shift_log.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='department',
            name='individual',
            field=models.BooleanField(default=False, verbose_name='Индивидуальный режим отчетов'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('department', 'employee', 'date')},
        ),
    ]
