# Generated by Django 4.2.23 on 2025-09-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0021_alter_dailyreport_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='individual',
        ),
        migrations.AddField(
            model_name='employee',
            name='individual_report',
            field=models.BooleanField(default=False, verbose_name='Индивидуальный отчет'),
        ),
    ]
