# Generated by Django 4.2.23 on 2025-10-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0022_remove_department_individual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('programmer', 'Программист'), ('tester', 'Тестировщик')], max_length=20, null=True, verbose_name='Роль'),
        ),
    ]
