# Generated by Django 4.2.23 on 2025-10-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0023_add_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Задание назначено'), ('shift_started', 'Смена началась'), ('shift_completed', 'Смена завершена'), ('task_completed', 'Задание завершено'), ('handover', 'Передача смены'), ('feature_created', 'Функционал создан'), ('feature_testing', 'Функционал на тестировании'), ('feature_rework', 'Функционал на доработке'), ('feature_completed', 'Функционал выполнен'), ('feature_done', 'Функционал завершен'), ('feature_comment_added', 'Добавлено замечание')], max_length=25, verbose_name='Тип уведомления'),
        ),
    ]
