# Generated by Django 4.2.23 on 2025-11-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0024_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_tasks', to='shift_log.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('rework', 'Возвращено на доработку'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='taskreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('rework', 'Возвращено на доработку'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], max_length=20, verbose_name='Статус'),
        ),
    ]
