# Generated by Django 4.2.23 on 2025-11-15 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0025_task_project_alter_task_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_projects', to='shift_log.employee', verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Проект задания',
                'verbose_name_plural': 'Проекты заданий',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='shift_log.taskproject', verbose_name='Проект'),
        ),
    ]
