# Generated by Django 4.2.23 on 2025-10-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecomment',
            name='rework_reason',
            field=models.TextField(blank=True, help_text='Причина возврата замечания на доработку', null=True, verbose_name='Причина возврата на доработку'),
        ),
    ]
