# Generated by Django 4.2.23 on 2025-10-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_log', '0024_alter_notification_notification_type'),
        ('testing', '0002_featurecomment_rework_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCommentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создано'), ('resolved', 'Решено'), ('returned_to_rework', 'Возвращено на доработку'), ('updated', 'Обновлено')], help_text='Тип действия с замечанием', max_length=30, verbose_name='Действие')),
                ('reason', models.TextField(blank=True, help_text='Причина изменения или дополнительный комментарий', verbose_name='Причина/Комментарий')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(help_text='Сотрудник, выполнивший действие', on_delete=django.db.models.deletion.CASCADE, related_name='comment_changes', to='shift_log.employee', verbose_name='Изменил')),
                ('comment', models.ForeignKey(help_text='Замечание, к которому относится история', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='testing.featurecomment', verbose_name='Замечание')),
            ],
            options={
                'verbose_name': 'История замечания',
                'verbose_name_plural': 'История замечаний',
                'ordering': ['-changed_at'],
            },
        ),
    ]
