# Generated by Django 4.2.23 on 2025-10-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_featurecommenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecomment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Дата завершения замечания', null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='featurecomment',
            name='status',
            field=models.CharField(choices=[('open', 'Открыто'), ('in_progress', 'В работе'), ('resolved', 'Решено'), ('completed', 'Завершено'), ('rework', 'На доработке')], default='open', help_text='Текущий статус замечания', max_length=20, verbose_name='Статус замечания'),
        ),
        migrations.AlterField(
            model_name='featurecomment',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text='Решено ли замечание (устаревшее поле, используйте status)', verbose_name='Решено'),
        ),
        migrations.AlterField(
            model_name='featurecommenthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Создано'), ('resolved', 'Решено'), ('completed', 'Завершено'), ('returned_to_rework', 'Возвращено на доработку'), ('updated', 'Обновлено')], help_text='Тип действия с замечанием', max_length=30, verbose_name='Действие'),
        ),
    ]
